### ISSUE TITLE
annot declare variable 'cli' to be of abstract type ...

### ISSUE THREAD

**Issue by freemanzwin** [tgtakaoka/libcli#5]
Thanks for sharing the library.
-------------------------------

Arduino IDE
ESP32 1.0.6

=========================================================================

D:\workspace\Arduino\libraries\libcli\src\libcli.cpp: In static member function 'static libcli::Cli& libcli::Cli::instance()':
D:\workspace\Arduino\libraries\libcli\src\libcli.cpp:27:16: error: cannot declare variable 'cli' to be of abstract type 'libcli::Cli'
     static Cli cli{impl::Impl::instance()};
                ^
In file included from D:\workspace\Arduino\libraries\libcli\src\libcli.cpp:17:0:
D:\workspace\Arduino\libraries\libcli\src\libcli.h:35:7: note:   because the following virtual functions are pure within 'libcli::Cli':
 class Cli final : public Stream {
       ^
In file included from C:\Users\abc\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.6\cores\esp32/Arduino.h:147:0,
                 from D:\workspace\Arduino\libraries\libcli\src\libcli.h:20,
                 from D:\workspace\Arduino\libraries\libcli\src\libcli.cpp:17:
**C:\Users\abc\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.6\cores\esp32/Stream.h:51:18: note: 	virtual void Stream::flush()
     virtual void flush() = 0;**
                  ^
exit status 1

**Comment by tgtakaoka** [comment]
> Which tool are you using and what version Arduino IDE, arduino-cli, paltformio? 
Aha, Arduino IDE ESP32 1.0.6, got it.

**Comment by tgtakaoka** [comment]
Hmm, ESP32 core's Stream.h is a bit different than others. It has 4 virtual methods defined comparing to other's 3 methods.

```
virtual void flush() = 0;
```
doesn't exist in others' class Stream.

A possible solution for this is implementing ```flush()``` and guard it with 
```
#if defined(ESP_PLATFORM)
#endif
```

**Comment by tgtakaoka** [comment]
Fixed in release 1.2.1.
